### ISSUE TITLE
vqCodebook-based speech recognition compatibility with Matlab 2015a

### ISSUE THREAD

**Issue by trychaga** [yashdv/Speech-Recognition#1]
what can be done to the posted code to run on Matlab version 8.5/2015
it is reporting Not enough input arguments. 
>> vqCodeBook
```
Error using vqCodeBook (line 12)
Not enough input arguments.
```

**Comment by yashdv** [comment]
Try Adding the correct number of arguments. "vqCodeBook" needs 2 arguments.

**Comment by trychaga** [comment]
I'm putting random arguments for d e.g. d=2 and d=4 where k = 16 and that leads to even more serious errors. I guess  I am missing the whole vector Quantization concept. Im using Matlab 2015.

**Comment by yashdv** [comment]
'd' is 2 dimensional not integers. Look at 'v' in the file 'train.m'
